services:
  user-service:
    image: openjdk:17-jdk-slim
    container_name: user-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - backend

networks:
  backend:
    driver: bridge
